### ISSUE TITLE
Permission issue when installing via ckan package install

### ISSUE THREAD

**Issue by rohith-aarini** [DataShades/ckanext-charts#23]
Hello everyone! After installing this extension, When creating a view I got an Internal Server Error on the ckan panel, which when checking in the logs I found it was a permission issue on the default package installation on the following folder ```/var/lib/ckan/default/charts_cache``` which states the uwgsi websever that comes default with the package install doesn't have permission on that folder. I have had some headache determining this issue.

I fixed it by running 
```sudo chown -R www-data:www-data /var/lib/ckan/default/charts_cache```
 
 I think this would be helpful to others if this is mentioned in the documentation. If there are any better ways to fix this issue I am open for discussion. Thank you.
 
 CKAN Version: 2.10
 Installation type: Package install
 Dataset loader: xloader
 OS: Ubuntu 22.04 LTS

**Comment by mutantsan** [comment]
The charts cache is being created inside the configured storage folder for CKAN.

https://docs.ckan.org/en/latest/maintaining/filestore.html#setup-file-uploads

According to the CKAN documentation, you had to give your web server user (`www-data`) permissions to this folder.

**Comment by rohith-aarini** [comment]
Thats awesome, thank you very much for pointing this. Could you please mention the same in the extension documentation like "you need to complete filestore steps in order for this plugin to work flawlessly", it would help newbies who just started working with ckan.

**Comment by iaroslav13** [comment]
Thanks @rohith-aarini, we will carefully consider your suggestion. We appreciate your feedback.
