### ISSUE TITLE
dependency on chanext-scheming?

### ISSUE THREAD

**Issue by brooks-eco** [DataShades/ckanext-charts#9]
Dependency on ckanext.scheming not declared in docs  but import in https://github.com/DataShades/ckanext-charts/blob/master/ckanext/charts/chart_builders/base.py line 222

```
ERROR LOG

File "/usr/lib/ckan/default/lib/python3.12/site-packages/ckanext/charts/chart_builders/base.py", line 222, in expand_schema_fields
    from ckanext.scheming.plugins import _expand_schemas
ModuleNotFoundError: No module named 'ckanext.scheming'
```

**Comment by mutantsan** [comment]
Thank you @brooks-eco, I'll include the `ckanext-scheming` requirements.
